version: '3.8'

services:
  nginx:
    image: nginx:alpine
    container_name: workprofile-nginx
    ports:
      - "8080:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./static:/usr/share/nginx/html/static
    depends_on:
      workprofile:
        condition: service_healthy
    networks:
      - nginx-network

  workprofile:
    build: 
      context: ..
    container_name: workprofile-app
    ports:
      - "5000:5000"
    environment:
      - DB_HOST=mysql
      - DB_USER=flaskapp
      - DB_PASS=flaskapp
      - DB_NAME=exampleDb
    depends_on:
      mysql:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "python", "-c", "import urllib.request; urllib.request.urlopen('http://localhost:5000/health')"]
      interval: 30s
      timeout: 10s
      retries: 5
    networks:
      - nginx-network
      - workprofile-network

  mysql:
    image: mysql:5.7
    container_name: mysql-db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword123
      MYSQL_DATABASE: exampleDb
      MYSQL_USER: flaskapp
      MYSQL_PASSWORD: flaskapp
    ports:
      - "3310:3306"
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql:ro
      - mysql-data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-prootpassword123"]
      interval: 10s
      timeout: 5s
      retries: 10
    networks:
      - workprofile-network

networks:
  nginx-network:
  workprofile-network:

volumes:
  mysql-data:
