name: WorkProfile CI/CD

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  IMAGE_NAME: workprofile-app

jobs:
  build-test:
    runs-on: ubuntu-latest

    steps:
    - name: Clone repository
      uses: actions/checkout@v3

    - name: Set up Docker
      uses: docker/setup-buildx-action@v3

    - name: Build Docker image
      run: |
        IMAGE_ID=ghcr.io/${{ github.repository_owner }}/${{ env.IMAGE_NAME }}
        IMAGE_ID=$(echo $IMAGE_ID | tr '[:upper:]' '[:lower:]')
        docker build -t $IMAGE_ID:latest .

    - name: Run container
      run: |
        IMAGE_ID=ghcr.io/${{ github.repository_owner }}/${{ env.IMAGE_NAME }}
        IMAGE_ID=$(echo $IMAGE_ID | tr '[:upper:]' '[:lower:]')
        docker run -d -p 5000:5000 --name app $IMAGE_ID:latest

    - name: Wait for container to be ready
      run: sleep 5

    - name: Test "/" endpoint
      run: curl --fail http://localhost:5000/

    - name: Test "/health" endpoint
      run: curl --fail http://localhost:5000/health

  publish:
    needs: build-test
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Docker
      uses: docker/setup-buildx-action@v3

    - name: Extract short SHA
      id: version
      run: echo "sha_tag=$(git rev-parse --short HEAD)" >> $GITHUB_OUTPUT

    - name: Log in to GitHub Container Registry
      run: echo "${{ secrets.GHCR_PAT }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin
